### ISSUE TITLE
how to convert text variable to principal

### ISSUE THREAD

**Issue by lauyoume** [dfinity/ic-repl#61]
```shell
let idtext = call canister.get_pid_text();
// principal idtext;
// how to convert idtext to a principal variable
```

**Comment by lauyoume** [comment]
> I would argue that it's not a good interface. Why cannot the canister return the principal directly?

Yes, It is not a good design,  it just an example to describe the problem aha~
It could change the design to solve this problem.

**Comment by chenyan2002** [comment]
Right. I'm a bit hesitated to support this, as this may encourage bad API design. You can basically asking to convert text to any candid type. There is probably a limit on how much we can support to avoid bad API.
