### ISSUE TITLE
ic-repl doesn't run on ubuntu 20.04

### ISSUE THREAD

**Issue by bitdivine** [dfinity/ic-repl#65]
On ubuntu 20.04, running the pre-built ic-repl fails with:
```
$ ~/Downloads/ic-repl-linux64
/home/max/Downloads/ic-repl-linux64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/max/Downloads/ic-repl-linux64)
/home/max/Downloads/ic-repl-linux64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/max/Downloads/ic-repl-linux64)
/home/max/Downloads/ic-repl-linux64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/max/Downloads/ic-repl-linux64)
```
This probably means that the binary wasn't statically linked, so it will only run on very specific versions of Linux.

**Comment by wusualis** [comment]
> On ubuntu 20.04, running the pre-built ic-repl fails with:
> 
> ```
> $ ~/Downloads/ic-repl-linux64
> /home/max/Downloads/ic-repl-linux64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/max/Downloads/ic-repl-linux64)
> /home/max/Downloads/ic-repl-linux64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/max/Downloads/ic-repl-linux64)
> /home/max/Downloads/ic-repl-linux64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/max/Downloads/ic-repl-linux64)
> ```
> 
> This probably means that the binary wasn't statically linked, so it will only run on very specific versions of Linux.


Hello, have you solve it yet?

**Comment by bitdivine** [comment]
I am afraid I haven't spent significant time on it yet.

For similar issues with e.g. ic-wasm I started by making tests.  So, the release has three stages:  build, smoke test on all supported platforms, then do the actual release:

![Screenshot from 2023-06-30 16-51-31](https://github.com/dfinity/ic-repl/assets/5982633/04ef435a-1caf-406c-be28-5871c5de58ab)

I would do the same here.  Then when we have proof in CI of what works, make changes and hopefully increase the number of supported platforms. Would you be open to this?

**Comment by bitdivine** [comment]
Note: Mac platform tests above are only intel.  For arm, we have to wait until this autumn/winter before runners are available on GitHub.

**Comment by wusualis** [comment]
That's great.

**Comment by bitdivine** [comment]
May I have access right to make a PR, please?  I don't seem to have them:

```
max@sinkpad:~/dfn/ic-repl/.github/workflows (6:30)$ git push --set-upstream origin smoke-test-releases
ERROR: Permission to dfinity/ic-repl.git denied to bitdivine.
fatal: Could not read from remote repository.
```

**Comment by wusualis** [comment]
> May I have access right to make a PR, please? I don't seem to have them:
> 
> ```
> max@sinkpad:~/dfn/ic-repl/.github/workflows (6:30)$ git push --set-upstream origin smoke-test-releases
> ERROR: Permission to dfinity/ic-repl.git denied to bitdivine.
> fatal: Could not read from remote repository.
> ```

@chenyan-dfinity He need your help.

**Comment by chenyan-dfinity** [comment]
@bitdivine IT is enforcing everyone to fork the repo. I'm working on reverting this decision for the whole org. Bear with me for some time.

**Comment by bitdivine** [comment]
No problem, I can fork.

**Comment by bitdivine** [comment]
So, these are the results now.  I will disable the test for Ubuntu 20.04, test that releases work and make a PR.

![Screenshot from 2023-06-30 20-34-49](https://github.com/dfinity/ic-repl/assets/5982633/0a401563-c263-4b94-816d-3283d5115ffc)

**Comment by bitdivine** [comment]
Actually, fixing 20.04 was easy, so I have included that in the PR.  However I cannot test releases; th erelease seems to try to publish to dfinity, if I understand what is happening correctly.

https://github.com/dfinity/ic-repl/pull/68

**Comment by bitdivine** [comment]
Thank you for the approval @chenyan-dfinity .  As an external contributor I cannot hit the merge button.  If one of you can do the honours, ideally after pushing a tag to make sure that the releases work, that would be much appreciated.

**Comment by bitdivine** [comment]
Closing, on the assumption that the next release will work with 20.04.
