### ISSUE TITLE
BUG: Testing the SNS requires us to use the system subnet type with the attached network config which breaks ic-repl

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/ic-repl#67]
Hi @chenyan-dfinity 

When testing the SNS workflow locally, we need to set the following in our network config,

```json
{
  "local": {
    "bind": "127.0.0.1:8080",
    "type": "ephemeral",
    "replica": {
      "subnet_type": "system"
    }
  }
}
```

This seems to be breaking ic-repl from running and gives the following output:
![image](https://github.com/dfinity/ic-repl/assets/7412443/af8024cc-5429-4619-b089-5c4885c5cebe)

Thoughts on how we can fix this? Thank you for your inputs :)

**Comment by chenyan-dfinity** [comment]
You can specify on the replica url as command-line flag: `ic-repl -r http://127.0.0.1:8080`
