### ISSUE TITLE
use ic-repl on staging environments

### ISSUE THREAD

**Issue by jake-beardo** [dfinity/ic-repl#86]
I need to use ic-repl with my staging environment 

i thought the command would look something like this:

#!/usr/bin/ic-repl -r staging
identity staging "./staging.pem";
import blah = "zzzzz-oqaaa-aaaan-ql32q-cai";
call poop.setPooWasm(file("./poo.wasm"));

and then 

ic-repl -r staging local_upload.sh

because my dfx.json looks like this

  "networks": {
    "staging": {
      "providers": [
        "https://icp0.io/"
      ],
      "type": "persistent"
    },
    
    any idea how to do this??

**Comment by chenyan-dfinity** [comment]
`ic-repl` doesn't read `dfx.json`. Looks like your staging network still points to the mainnet, so either `ic-repl -r https://icp0.io` or `ic-repl -r ic` would work.
